databases:
  - name: budgetlydb
    databaseName: postgres_sql_x4sz
    user: postgres_sql_x4sz_user

services:
  - type: web
    name: budgetly
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetappdb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false